import * as THREE from "https://unpkg.com/three@0.160.0/build/three.module.js";

export const GAME_CONFIG = {
    visuals: {
        background: 0x05060a,
        grid: { size: 400, divisions: 80, color1: 0x2a3b5f, color2: 0x111827 },
        stars: { count: 1500, radius: 900, size: 1.2 },
        light: {
            directional: { color: 0xffffff, intensity: 1.1, position: [10, 20, 10] },
            ambient: { color: 0x4a4a4a },
        },
    },
    camera: {
        fov: 60,
        near: 0.1,
        far: 2000,
        offset: new THREE.Vector3(0, 3, -12),
        smoothing: 0.12,
        smoothingDeadzone: 0.2,
        smoothingMaxStep: 8,
        smoothingMaxLag: 6,
        shake: { duration: 0.28, strength: 0.35 },
    },
    minimap: { size: 180, range: 180, radius: 72 },
    gameplay: {
        lives: 5,
        respawnDelay: 3.0,
        timeLimit: 300,
        killTarget: 20,
        comboWindow: 10,
        comboBonus: 50,
        allyDeathLimit: 5,
    },
    player: {
        maxSpeed: 80,
        acceleration: 40,
        boostMultiplier: 2.0,
        boostFuel: 5.0,
        boostRegenDelay: 1.0,
        boostRegenRate: 0.5,
        muzzleOffset: new THREE.Vector3(0.6, 1.4, 0.9),
    },
    targeting: {
        maxDistance: 300,
        fovDegrees: 30,
        lockOffDistance: 350,
    },
    weapons: {
        playerLaser: {
            damage: 20,
            range: 500,
            fireRate: 8,
            beamColor: 0x9fd7ff,
            beamEmissive: 0x5ad1ff,
            beamRadius: 1,
            beamDuration: 0.14,
        },
        bazooka: {
            damage: 50,
            range: 520,
            fireRate: 1.2,
            clipSize: 5,
            cooldownDuration: 7.5,
            beamColor: 0xffd18a,
            beamEmissive: 0xff8f3a,
            beamRadius: 10,
            beamDuration: 0.16,
        },
        enemyLaser: {
            damage: 12,
            range: 400,
            fireRate: 2,
            beamColor: 0xff9f9f,
            beamEmissive: 0xff4f4f,
            beamRadius: 0.07,
            beamDuration: 0.14,
        },
    },
    battleships: {
        stats: {
            maxHp: 1200,
            maxShield: 0,
            colliderRadius: 16,
        },
        beam: {
            damage: 20,
            range: 520,
            fireRate: 2.2,
            beamColor: 0xffb0b0,
            beamEmissive: 0xff6b6b,
            beamRadius: 0.18,
            beamDuration: 0.18,
            inaccuracyDeg: 10,
            enrageDuration: 6.0,
            enrageFireRateMult: 1.8,
            enrageDamageMult: 1.35,
        },
        spawn: {
            enemyInterval: 9.5,
            decoyInterval: 14,
            allyInterval: 9.5,
            maxEnemyActive: 15,
            maxAllyActive: 7,
            maxDecoyActive: 6,
        },
        positions: {
            enemy: [
                [120, 10, 420],
                [-140, -15, 420],
            ],
            ally: [
                [140, 5, -420],
                [-120, -8, -420],
            ],
        },
    },
    allies: {
        types: {
            wing: {
                name: "Wing",
                maxHp: 70,
                maxShield: 40,
                score: 0,
                fireRate: 2,
                palette: {
                    body: 0x5ab0ff,
                    core: 0x0b2a52,
                    panel: 0x8fd4ff,
                    glow: 0x7ad7ff,
                },
                ai: {
                    chaseDistance: 420,
                    attackDistance: 250,
                    attackAngleDeg: 22,
                    standoffDistance: 220,
                    standoffBand: 40,
                },
            },
        },
    },
    decoys: {
        respawnDelay: 0,
    },
    enemies: {
        spawn: {
            maxActive: 15,
            baseInterval: 10,
            minInterval: 5,
            radiusRange: [120, 260],
            heightRange: [-20, 20],
        },
        types: {
            grunt: {
                name: "Grunt",
                maxHp: 95,
                maxShield: 60,
                score: 100,
                fireRate: 2,
                ai: {
                    chaseDistance: 520,
                    attackDistance: 330,
                    attackAngleDeg: 26,
                    standoffDistance: 260,
                    standoffBand: 40,
                },
            },
            ace: {
                name: "Ace",
                maxHp: 200,
                maxShield: 120,
                score: 250,
                fireRate: 2,
                ai: {
                    chaseDistance: 600,
                    attackDistance: 370,
                    attackAngleDeg: 28,
                    standoffDistance: 300,
                    standoffBand: 50,
                },
            },
        },
    },
    obstacles: {
        count: 30,
        radiusRange: [8, 30],
        distanceRange: [200, 800],
    },
    spatialIndex: {
        cellSize: 50,
    },
};
